messagesLang: ru

startLivesCount: 9
startPoints: 0
healthLimit: 2

reward: 2
rewardMultiplier: 2
threshold: 50
totemCost: 20

startLivePrice: 100
nextLivePrice: 50

minPayment: 1

actionbarStats: true
subtitleDeathMessage: true
advancementRewardInChat: true

actionBarFormat: "[{\"text\":\"{LIVES}\",\"color\":\"#{LIVES_COLOR}\"},{\"text\":\" | \",\"bold\":true,\"color\":\"dark_gray\"},{\"text\":\"{POINTS}\",\"color\":\"yellow\"},{\"text\":\" | \",\"bold\":true,\"color\":\"dark_gray\"},{\"text\":\"{ADVANCEMENTS}\",\"color\":\"aqua\"}]"

onSpectatorCommands:
  - "gamemode spectator %player_name%"

pointsTimer:
  enabled: false
  timer: "1h" # h - час m - минута s - секунда
  reward: 15