name: LLivesHardcore
main: com.lmpx.lliveshardcore.Main
version: "1.0.E1"
author: LIMPIX31
softdepend:
  - PlaceholderAPI
api-version: 1.16
commands:
  llh:
    aliases:
      - 1hp
  buylife:
    aliases:
      - blife
      - buyl
  paypoints:
    aliases:
      - pp
permissions:
  llh.*:
    children:
      - llh.pluginCommand
      - llh.reloadConfig
      - llh.setLives
      - llh.setPoints
      - llh.buyLife