name: LLivesHardcore
main: com.lmpx.lliveshardcore.Main
version: '1.1.4'
author: LIMPIX31
softdepend:
  - PlaceholderAPI
api-version: 1.18
commands:
  llh:
    aliases:
      - 1hp
  buylife:
    aliases:
      - blife
      - buyl
  paypoints:
    aliases:
      - pp
  getprice:
    usage: /getprice
permissions:
  llh.*:
    children:
      - llh.pluginCommand
      - llh.reloadConfig
      - llh.setLives
      - llh.setPoints
      - llh.setBoughtLives
      - llh.setAdvsc
      - llh.buyLife
      - llh.buylifefornpc
      - llh.getprice